### ISSUE TITLE
"double" serialization / deserialization issue

### ISSUE THREAD

**Issue by rlasjunies** [Tailslide/fluxor-persist#3]
Hi,

 I've got a strange issue.

 The middleware was not able to rehydrate simple object
`...
The JSON value could not be converted to Sudoku.Store.Counter.StateCounter
...`

I succeeded to overcome the issue by updating the method `LocalStateStorage.GetStateJsonAsync`

The problem seems coming from `await LocalStorage.GetItemAsStringAsync(statename)`

That I replaced successfully by `await LocalStorage.GetItemAsync<string>(statename)`

Sincerely,

**Comment by Tailslide** [comment]
That’s weird.. I believe I am using that local storage class to handle some pretty complex states. Are you able to post an example project with the issue?

**Comment by Tailslide** [comment]
Just noticed that the new version of Blazored.localstorage seems to break things. If you downgrade Blazored to V3.0 instead of V4.0 everything seems to run OK.  Not sure if it's a bug or what... will have an update out to the sample app when I track it down.

**Comment by Tailslide** [comment]
See https://github.com/Blazored/LocalStorage/issues/140
