### ISSUE TITLE
SubscribeToAction<InitializePersistMiddlewareResultSuccessAction> not working after upgrade to .net6

### ISSUE THREAD

**Issue by fabiankuehne** [Tailslide/fluxor-persist#4]
I upgraded my blazor application to .net6, now following subscription is not working any more:

`            
ActionSubscriber.SubscribeToAction<InitializePersistMiddlewareResultSuccessAction>(this, result =>
            {
            });
`
Look's like it's never triggered.

Is it possible to upgrade the package, that it works with .net6?

Thanks!

**Comment by Tailslide** [comment]
Yes I will look at this when I have some free cycles might be a few days.

**Comment by Tailslide** [comment]
Got to it early!
