### ISSUE TITLE
Fluxor persist not usable in non blazor projects

### ISSUE THREAD

**Issue by davidnajar** [Tailslide/fluxor-persist#6]
**Is your feature request related to a problem? Please describe.** 

I'm currently sharing the same codebase between a blazor and Xamarin app. The MVVM library uses fluxor to do the state management, but as fluxor persist  targets net6 this can't be added to the netstandard shared library

**Describe the solution you'd like**

Fluxor.Persist should target netstandard2.0, same as Fluxor itself

**Describe alternatives you've considered**

Of course when .NET maui is released (net6.0) this will not be an issue for mobile apps

**Additional context**
-

**Comment by davidnajar** [comment]
see PR #5

**Comment by Tailslide** [comment]
Thanks for tackling this works great!  It's published now.
