### ISSUE TITLE
Loosing state on navigating away

### ISSUE THREAD

**Issue by melvin78** [Tailslide/fluxor-persist#8]
Hi, This is a really great library and i feel like it will solve my issue just need one affirmation. This is more of a question really. I am starting out on blazor and am using fluxor for my state management. Everything works fine but when i navigating away from a component i loose all the state, is that expected behavior when using fluxor? and i mean navigating away and not a page refresh. I believe in blazor on navigating  away the component is usually destroyed and a new one created meaning all state will be lost. I figured Fluxor will help maintain the state but it seems thats not the case or there could be something i am missing?

regards

**Comment by Tailslide** [comment]
@melvin78 , Fluxor should not lose state navigating between pages in your blazor app.  You will want to get this resolved before introducing the added complexity of fluxor-persist to your project.  You can find a great support community here:

https://gitter.im/mrpmorris/fluxor

**Comment by melvin78** [comment]
Hi

**Comment by melvin78** [comment]
I was able to find where the issue was , i was not really keen on how reducers work. Thanks
